repos:
  # Limpieza basica
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace   # Borrar espacios vacíos al final de las líneas
      - id: end-of-file-fixer     # Asegura que todo archivo termine con una línea vacía
      - id: check-yaml            # Verifica que tus archivos YAML no tengan errores de sintaxis

  # Politica de commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.3.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]      # Se activa despues de escribir el mensaje
        args: [                   # Verifica que inicie con las convenciones definidas
          "feat",
          "fix",
          "infra",
          "docs",
          "refactor",
          "chore",
          "test",
          "style",
          "security"
        ]
